import React, {useState} from 'react';
import {Alert, Platform, Pressable, ScrollView, StatusBar, StyleSheet, Text, View, useWindowDimensions} from 'react-native';

const RED='#ff1616', BG='#050505', PANEL='#101010', MUTED='#9b9b9b', GREEN='#00ef78';
const TOP_INSET=Platform.OS==='android' ? (StatusBar.currentHeight || 24) : 10;

const stats=[['▣','1.248','Mensagens Hoje'],['⚙','12','Automações Ativas'],['▤','389','Testes Gerados'],['ϟ','2.756','Ações Executadas']];
const modules=[['M','Masterflix','Streaming e Acessos'],['CLOUD','Automation Cloud','Keys e Ativações'],['IBO','Master IBO','Resets e Gerenciamento']];
const recent=[['▣','Cliente pediu teste','Via WhatsApp','Masterflix gerou acesso','Acesso enviado com sucesso','14:26'],['↻','Solicitou reset','Via Painel','IBO resetado','Dados atualizados','14:12'],['☁','Ativação XCloud','Via WhatsApp','Key cadastrada','Ativação concluída','13:58']];

function Soon(name){Alert.alert(name,'Essa função será conectada ao backend na próxima etapa.');}
function Dot({small=false}){return <View style={[s.dot,small&&s.dotSmall]}/>}
function XcoreLogo(){return <View style={s.brand}><View style={s.brandIcon}><Text style={s.brandIconX}>X</Text></View><View style={s.brandWord}><View style={s.wordRow}><Text style={s.brandX}>X</Text><Text style={s.brandCore}>CORE</Text></View><Text style={s.brandSub}>CENTRAL DE AUTOMAÇÃO</Text></View></View>}
function Section({title,right}){return <View style={s.section}><View style={s.sectionLeft}><View style={s.redBar}/><Text style={s.sectionTitle}>{title}</Text></View>{right}</View>}
function CloudMark(){return <View style={s.cloudMark}><View style={[s.cloudPart,s.cloudA]}/><View style={[s.cloudPart,s.cloudB]}/><View style={[s.cloudPart,s.cloudC]}/><View style={s.cloudBase}/></View>}
function Stat({item,width}){return <View style={[s.stat,{width}]}><View style={s.statCorner}/><View style={s.statGlow}/><View style={s.iconBox}><Text style={s.icon}>{item[0]}</Text></View><Text adjustsFontSizeToFit numberOfLines={1} minimumFontScale={0.72} style={s.value}>{item[1]}</Text><Text numberOfLines={2} style={s.label}>{item[2]}</Text><View style={s.track}><View style={s.trackOn}/></View></View>}
function Module({item,width}){return <Pressable onPress={()=>Soon(item[1])} style={({pressed})=>[s.module,{width},pressed&&s.pressed]}><View style={s.moduleCut}/><View style={s.moduleTopAccent}/><View style={s.moduleBottomAccent}/><View style={s.moduleLogo}>{item[0]==='CLOUD'?<CloudMark/>:<Text style={[s.moduleLogoText,item[0]==='IBO'&&s.ibo]}>{item[0]}</Text>}</View><Text numberOfLines={1} adjustsFontSizeToFit minimumFontScale={0.72} style={s.moduleTitle}>{item[1]}</Text><Text numberOfLines={1} adjustsFontSizeToFit minimumFontScale={0.7} style={s.moduleSub}>{item[2]}</Text><View style={s.moduleBottom}><View style={s.online}><Dot small/><Text style={s.onlineText}>Online</Text></View><Text style={s.chev}>›</Text></View></Pressable>}
function Trigger({item,last}){return <><View style={s.trigger}><View style={s.triggerAccent}/><View style={s.triggerIcon}><Text style={s.triggerIconText}>{item[0]}</Text></View><View style={s.triggerSide}><Text numberOfLines={1} style={s.main}>{item[1]}</Text><Text numberOfLines={1} style={s.meta}>{item[2]}</Text></View><Text style={s.arrow}>→</Text><View style={[s.triggerSide,{flex:1.18}]}><Text numberOfLines={1} style={s.main}>{item[3]}</Text><Text numberOfLines={1} style={s.meta}>{item[4]}</Text></View><Text style={s.time}>{item[5]}</Text><Text style={s.dots}>⋮</Text></View>{!last&&<View style={s.divider}/>}</>}
function Nav({icon,label,active,badge,onPress}){return <Pressable onPress={onPress} style={s.navItem}><View><Text style={[s.navIcon,active&&s.navActive]}>{icon}</Text>{badge&&<View style={s.badge}><Text style={s.badgeText}>{badge}</Text></View>}</View><Text numberOfLines={1} style={[s.navLabel,active&&s.navLabelActive]}>{label}</Text>{active&&<View style={s.navLine}/>}</Pressable>}

export default function App(){
  const {width}=useWindowDimensions();
  const [tab,setTab]=useState('Início');
  const pad=width<390?12:15, statGap=width<390?6:8, moduleGap=7, available=width-pad*2;
  const statW=(available-statGap*3)/4, moduleW=(available-moduleGap*2)/3;
  return <View style={[s.safe,{paddingTop:TOP_INSET}]}><StatusBar barStyle="light-content" backgroundColor={BG} translucent={false}/><View style={s.root}>
    <View pointerEvents="none" style={s.sideRailLeft}/><View pointerEvents="none" style={s.sideRailRight}/>
    <ScrollView style={s.scroll} contentContainerStyle={[s.content,{paddingHorizontal:pad}]} showsVerticalScrollIndicator={false}>
      <View style={s.header}><View style={s.topLine}/><XcoreLogo/><Pressable onPress={()=>Soon('Notificações')} style={s.bell}><Text style={s.bellText}>♢</Text><View style={s.notify}/></Pressable></View>
      <View style={s.welcome}><View style={s.welcomeText}><Text style={s.hello}>Olá, <Text style={s.bold}>Admin</Text></Text><Text style={s.subHello}>Tudo funcionando perfeitamente!</Text></View><View style={s.hero}><Text style={s.heroMark}>⌁</Text><View><Text style={s.heroText}>AUTOMAÇÃO</Text><Text style={s.heroText}>SEM LIMITES</Text></View></View></View>
      <View style={[s.stats,{gap:statGap}]}>{stats.map((x,i)=><Stat key={i} item={x} width={statW}/>)}</View>
      <Section title="Módulos" right={<Pressable onPress={()=>Soon('Status dos módulos')} style={s.allOnline}><Dot/><Text style={s.allOnlineText}>Todos online</Text><Text style={s.chevSmall}>›</Text></Pressable>}/>
      <View style={[s.moduleRow,{gap:moduleGap}]}>{modules.map((x,i)=><Module key={i} item={x} width={moduleW}/>)}</View>
      <Section title="Gatilhos Recentes" right={<Pressable onPress={()=>Soon('Gatilhos')} style={s.allOnline}><Text style={s.allOnlineText}>Ver todos</Text><Text style={s.chevSmall}>›</Text></Pressable>}/>
      <View style={s.recent}>{recent.map((x,i)=><Trigger key={i} item={x} last={i===recent.length-1}/>)}</View>
      <Pressable onPress={()=>Soon('Criar automação')} style={({pressed})=>[s.create,pressed&&s.pressed]}><View style={s.createGlow}/><View style={s.createCornerL}/><View style={s.createCornerR}/><Text style={s.plus}>＋</Text><Text style={s.createText}>Criar automação</Text><Text style={s.createArrow}>›</Text></Pressable>
      <View style={s.slogan}><View style={s.sloganLine}/><Text style={s.sloganText}>MAIS AUTOMAÇÃO. MAIS RESULTADOS.</Text><View style={s.sloganLine}/></View>
    </ScrollView>
    <View style={s.nav}><View style={s.navTop}/><Nav icon="⌂" label="Início" active={tab==='Início'} onPress={()=>setTab('Início')}/><Nav icon="ϟ" label="Gatilhos" active={tab==='Gatilhos'} onPress={()=>{setTab('Gatilhos');Soon('Gatilhos')}}/><Nav icon="▣" label="Mensagens" badge="3" active={tab==='Mensagens'} onPress={()=>{setTab('Mensagens');Soon('Mensagens')}}/><Nav icon="⚙" label="Config" active={tab==='Config'} onPress={()=>{setTab('Config');Soon('Configurações')}}/></View>
  </View></View>
}

const s=StyleSheet.create({
 safe:{flex:1,backgroundColor:BG},root:{flex:1,backgroundColor:BG},scroll:{flex:1},content:{paddingTop:2,paddingBottom:8},bold:{fontWeight:'900'},pressed:{opacity:.76},
 sideRailLeft:{position:'absolute',left:0,top:115,bottom:75,width:2,backgroundColor:RED,opacity:.48,zIndex:5},sideRailRight:{position:'absolute',right:0,top:115,bottom:75,width:2,backgroundColor:RED,opacity:.48,zIndex:5},
 header:{height:72,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:'#261010',position:'relative'},topLine:{position:'absolute',top:0,left:'36%',width:'28%',height:2,backgroundColor:RED,shadowColor:RED,shadowOpacity:1,shadowRadius:9,elevation:8},
 brand:{flexDirection:'row',alignItems:'center',flex:1,maxWidth:260},brandIcon:{width:49,height:49,borderRadius:11,borderWidth:1,borderColor:'#752020',backgroundColor:'#0c0c0c',alignItems:'center',justifyContent:'center',marginRight:7,transform:[{rotate:'-2deg'}]},brandIconX:{fontSize:37,fontWeight:'900',fontStyle:'italic',color:'#e8e8e8',textShadowColor:RED,textShadowRadius:7},brandWord:{justifyContent:'center'},wordRow:{flexDirection:'row',alignItems:'center'},brandX:{fontSize:27,fontWeight:'900',fontStyle:'italic',color:RED,marginRight:1,textShadowColor:'#780000',textShadowRadius:5},brandCore:{fontSize:27,fontWeight:'900',fontStyle:'italic',color:'#f0f0f0',letterSpacing:-1.2},brandSub:{color:'#cfcfcf',fontSize:5.8,fontWeight:'700',letterSpacing:2.3,marginTop:-2},
 bell:{width:40,height:40,borderRadius:10,borderWidth:1,borderColor:'#494949',backgroundColor:'#111',alignItems:'center',justifyContent:'center',position:'relative'},bellText:{color:'#ddd',fontSize:24,lineHeight:27},notify:{position:'absolute',right:5,top:5,width:8,height:8,borderRadius:4,backgroundColor:RED},
 welcome:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8,marginTop:9,marginBottom:9},welcomeText:{flex:1,minWidth:0},hello:{color:'#f5f5f5',fontSize:24},subHello:{color:MUTED,fontSize:11.5,marginTop:1},hero:{width:123,minHeight:55,borderWidth:1,borderColor:RED,backgroundColor:'#100505',paddingHorizontal:8,paddingVertical:7,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:5,transform:[{skewX:'-7deg'}]},heroMark:{color:RED,fontSize:22,fontWeight:'800',transform:[{skewX:'7deg'}]},heroText:{color:'#eee',fontSize:7.7,fontWeight:'900',letterSpacing:1.7,transform:[{skewX:'7deg'}]},
 stats:{flexDirection:'row',marginBottom:12},stat:{height:108,backgroundColor:PANEL,borderWidth:1,borderColor:'#505050',borderRadius:10,paddingHorizontal:7,paddingVertical:7,overflow:'hidden'},statCorner:{position:'absolute',right:-5,top:-5,width:26,height:26,borderLeftWidth:1.5,borderBottomWidth:1.5,borderColor:'#7e1818',transform:[{rotate:'45deg'}]},statGlow:{position:'absolute',width:54,height:54,right:-20,bottom:-18,borderRadius:35,backgroundColor:RED,opacity:.12},iconBox:{width:30,height:30,borderRadius:7,borderWidth:1,borderColor:'#841414',backgroundColor:'#130707',alignItems:'center',justifyContent:'center',marginBottom:5},icon:{color:'#ff3b3b',fontWeight:'900',fontSize:15},value:{color:'#fff',fontSize:18.5,lineHeight:21,fontWeight:'900'},label:{color:'#ddd',fontSize:8.2,lineHeight:10,minHeight:19,marginTop:1},track:{height:3,backgroundColor:'#242424',borderRadius:3,marginTop:4},trackOn:{width:'68%',height:'100%',backgroundColor:RED,borderRadius:3},
 section:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:0,marginBottom:7},sectionLeft:{flexDirection:'row',alignItems:'center',flexShrink:1},redBar:{width:4,height:25,borderRadius:2,backgroundColor:RED,marginRight:8},sectionTitle:{color:'#fff',fontSize:19.5,fontWeight:'900'},allOnline:{flexDirection:'row',alignItems:'center',gap:4},allOnlineText:{color:'#d8d8d8',fontSize:10.5},dot:{width:9,height:9,borderRadius:5,backgroundColor:GREEN},dotSmall:{width:7,height:7,borderRadius:4},chevSmall:{color:'#aaa',fontSize:20,lineHeight:21},
 moduleRow:{flexDirection:'row',marginBottom:13},module:{height:128,backgroundColor:'#0c0c0c',borderWidth:1,borderColor:'#565656',borderRadius:10,paddingHorizontal:8,paddingVertical:8,overflow:'hidden'},moduleCut:{position:'absolute',right:-8,top:-8,width:34,height:34,borderLeftWidth:2,borderBottomWidth:2,borderColor:RED,backgroundColor:'#180707',transform:[{rotate:'45deg'}]},moduleTopAccent:{position:'absolute',left:0,top:0,width:31,height:2,backgroundColor:'#8b8b8b'},moduleBottomAccent:{position:'absolute',left:0,bottom:0,width:33,height:2,backgroundColor:RED,opacity:.8},moduleLogo:{height:42,alignItems:'center',justifyContent:'center'},moduleLogoText:{color:'#e72d2d',fontSize:37,lineHeight:41,fontWeight:'900',textShadowColor:'#6b0808',textShadowRadius:6},ibo:{color:'#eee',fontSize:24,fontStyle:'italic'},moduleTitle:{color:'#fff',fontSize:11.5,lineHeight:13,fontWeight:'900',marginTop:1},moduleSub:{color:'#979797',fontSize:7.6,lineHeight:9,marginTop:2},moduleBottom:{flex:1,flexDirection:'row',alignItems:'flex-end',justifyContent:'space-between'},online:{borderWidth:1,borderColor:'#12462d',backgroundColor:'#071a10',borderRadius:14,paddingHorizontal:6,paddingVertical:3,flexDirection:'row',alignItems:'center',gap:4},onlineText:{color:GREEN,fontSize:8.7},chev:{color:'#ddd',fontSize:22,lineHeight:21},
 cloudMark:{width:46,height:30,position:'relative'},cloudPart:{position:'absolute',borderWidth:1.7,borderColor:'#ff3737',backgroundColor:'#0f0f0f'},cloudA:{width:21,height:21,borderRadius:12,left:3,top:8},cloudB:{width:25,height:25,borderRadius:14,left:13,top:2},cloudC:{width:20,height:20,borderRadius:11,right:2,top:9},cloudBase:{position:'absolute',left:6,right:4,bottom:1,height:11,borderWidth:1.7,borderColor:'#ff3737',backgroundColor:'#0f0f0f',borderRadius:7},
 recent:{borderWidth:1,borderColor:'#414141',borderRadius:10,backgroundColor:'#0b0b0b',overflow:'hidden',marginBottom:11},trigger:{minHeight:49,paddingHorizontal:7,paddingVertical:6,flexDirection:'row',alignItems:'center',gap:4,position:'relative'},triggerAccent:{position:'absolute',left:0,top:8,bottom:8,width:2,backgroundColor:RED,opacity:.82},triggerIcon:{width:30,height:30,borderRadius:15,borderWidth:1,borderColor:RED,backgroundColor:'#100606',alignItems:'center',justifyContent:'center'},triggerIconText:{color:'#ff3c3c',fontSize:12.5,fontWeight:'900'},triggerSide:{flex:1,minWidth:0},main:{color:'#f2f2f2',fontSize:9.7,fontWeight:'800'},meta:{color:'#929292',fontSize:7.8,marginTop:1},arrow:{color:RED,fontSize:16},time:{color:'#999',fontSize:7.8,width:29},dots:{color:'#bdbdbd',fontSize:17},divider:{height:1,backgroundColor:'#292929',marginLeft:42},
 create:{minHeight:55,borderWidth:1.5,borderColor:'#ff3838',backgroundColor:'#370606',borderRadius:9,flexDirection:'row',alignItems:'center',justifyContent:'center',overflow:'hidden',marginBottom:7},createGlow:{position:'absolute',width:'66%',height:78,top:-23,left:'17%',borderRadius:55,backgroundColor:RED,opacity:.2},createCornerL:{position:'absolute',left:6,top:6,bottom:6,width:2,backgroundColor:'#ff6060'},createCornerR:{position:'absolute',right:6,top:6,bottom:6,width:2,backgroundColor:'#ff6060'},plus:{color:'#fff',fontSize:30,fontWeight:'300',marginRight:8},createText:{color:'#fff',fontSize:17,fontWeight:'900'},createArrow:{color:'#fff',fontSize:26,marginLeft:9},
 slogan:{flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7,marginBottom:2},sloganLine:{width:20,height:1.5,backgroundColor:RED},sloganText:{color:'#bdbdbd',fontSize:6.5,fontWeight:'800',letterSpacing:1.45},
 nav:{height:63,backgroundColor:'#080808',borderTopWidth:1,borderTopColor:'#3b3b3b',flexDirection:'row',alignItems:'stretch',justifyContent:'space-around',paddingHorizontal:3,position:'relative'},navTop:{position:'absolute',top:-1,left:'8%',width:'17%',height:2,backgroundColor:RED},navItem:{flex:1,alignItems:'center',justifyContent:'center',position:'relative'},navIcon:{color:'#9b9b9b',fontSize:21,fontWeight:'700',lineHeight:23},navActive:{color:'#fff',textShadowColor:RED,textShadowRadius:8},navLabel:{color:'#999',fontSize:8.3,marginTop:1},navLabelActive:{color:'#fff',fontWeight:'800'},navLine:{position:'absolute',bottom:2,width:33,height:2,borderRadius:2,backgroundColor:RED},badge:{position:'absolute',right:-9,top:-6,minWidth:16,height:16,borderRadius:8,backgroundColor:RED,alignItems:'center',justifyContent:'center',paddingHorizontal:3},badgeText:{color:'#fff',fontSize:8.5,fontWeight:'900'}
});
