name: Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.7

      - name: Criar keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > master-flow-release.jks

      - name: Build APK Release Assinado
        run: gradle assembleRelease

      - name: Enviar APK Release
        uses: actions/upload-artifact@v4
        with:
          name: Master-Flow-release
          path: app/build/outputs/apk/release/*.apk
