name: Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Verificar projeto Gradle
        run: ls -la

      - name: Dar permissão ao Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Build APK Debug
        run: ./gradlew assembleDebug

      - name: Enviar APK
        uses: actions/upload-artifact@v4
        with:
          name: Master-Flow-debug
          path: app/build/outputs/apk/debug/*.apk
